spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    defaults:
      type-mappings:
        - message-type: org.example.User
          schema-info:
            schema-type: JSON
